# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 22:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('additive_write', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('copy_write', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('process_class', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('property_type', models.PositiveIntegerField(choices=[(1, 'boolean'), (2, 'number'), (3, 'integer')], default=2)),
                ('default_value', models.FloatField(default=0.0)),
                ('max_value', models.FloatField(null=True)),
                ('min_value', models.FloatField(null=True)),
                ('property_value', models.FloatField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('num_steps', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Simulation')),
            ],
        ),
        migrations.AddField(
            model_name='outputconnector',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merlin_api.UnitType'),
        ),
        migrations.AddField(
            model_name='output',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Simulation'),
        ),
        migrations.AddField(
            model_name='output',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merlin_api.UnitType'),
        ),
        migrations.AddField(
            model_name='inputconnector',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merlin_api.OutputConnector'),
        ),
        migrations.AddField(
            model_name='inputconnector',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merlin_api.UnitType'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Simulation'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.InputConnector'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.OutputConnector'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Simulation'),
        ),
        migrations.AlterUniqueTogether(
            name='unittype',
            unique_together=set([('sim', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('sim', 'value')]),
        ),
    ]
