# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Entity'),
        ),
    ]
