# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0002_auto_20160331_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimOutputConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('additive_write', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlin_api.Output')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merlin_api.OutputConnector')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merlin_api.UnitType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
