# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0004_auto_20160331_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_source',
            field=models.BooleanField(default=False),
        ),
    ]
