# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0007_auto_20160403_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='display_pos_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='display_pos_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='display_pos_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='display_pos_y',
            field=models.FloatField(null=True),
        ),
    ]
