# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0008_auto_20160405_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputconnector',
            name='copy_write',
        ),
        migrations.AddField(
            model_name='outputconnector',
            name='apportion_rule',
            field=models.PositiveIntegerField(choices=[(1, 'copy_write'), (2, 'weighted'), (3, 'absolute')], default=2),
        ),
    ]
