# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0009_auto_20160406_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
