# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0010_simulation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 1, 1, 0, 0)),
        ),
    ]
