# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0012_auto_20160412_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None),
        ),
    ]
