# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0014_auto_20160413_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='target',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
