# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0015_auto_20160419_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=1)),
                ('actions', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField(null=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='merlin_api.Simulation')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='merlin_api.Scenario'),
        ),
    ]
