# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0019_auto_20160427_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('start', models.DateField(default=datetime.datetime(2016, 1, 1, 0, 0))),
                ('end', models.DateField(default=datetime.datetime(2016, 4, 1, 0, 0))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='merlin_api.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
