# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0020_project_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
