# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0020_project_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
