# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0021_auto_20160502_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphase',
            old_name='end',
            new_name='value',
        ),
    ]
