# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0022_auto_20160503_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='merlin_api.Project'),
        ),
    ]
