# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0023_auto_20160503_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_ringfenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
