# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0025_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='merlin_api.Scenario'),
        ),
    ]
