# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0027_auto_20160505_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scenario',
        ),
        migrations.AddField(
            model_name='projectphase',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_phases', to='merlin_api.Scenario'),
        ),
    ]
