# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0028_auto_20160506_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphase',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='projectphase',
            old_name='cost',
            new_name='investment_cost',
        ),
        migrations.RenameField(
            model_name='projectphase',
            old_name='start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='achievability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='attractiveness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='dependencies',
            field=models.ManyToManyField(related_name='required_by', to='merlin_api.Project'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='service_cost',
            field=models.IntegerField(default=0),
        ),
    ]
