# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0029_auto_20160510_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='processproperty',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
