# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0030_processproperty_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None),
        ),
    ]
