# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0031_output_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
