# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0032_auto_20160523_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dependencies',
            field=models.ManyToManyField(default=None, related_name='required_by', to='merlin_api.Project'),
        ),
    ]
