# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0033_auto_20160525_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 1, 0, 0)),
        ),
    ]
