# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0034_auto_20160526_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='capitalization',
            field=models.FloatField(default=0.0),
        ),
    ]
