# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlin_api', '0035_projectphase_capitalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='output',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='simoutputconnector',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='simoutputconnector',
            name='source',
        ),
        migrations.RemoveField(
            model_name='simoutputconnector',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='sim_output',
        ),
        migrations.RemoveField(
            model_name='inputconnector',
            name='source',
        ),
        migrations.AddField(
            model_name='entity',
            name='is_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='merlin_api.InputConnector'),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='SimOutputConnector',
        ),
    ]
